// Generated ~200-page mock (about 3,000 blocks) for scrolling / navigation
// performance. Deterministic: same seed → same document and same diff ids.

import type { DiffResult } from '../model/diff';
import { H, LI, P, PairBuilder, Title } from './builder';

function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let x = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    x = (x + Math.imul(x ^ (x >>> 7), 61 | x)) ^ x;
    return ((x ^ (x >>> 14)) >>> 0) / 4294967296;
  };
}

const SUBJECTS = ['The investigator', 'The sponsor', 'Each participant', 'The study team', 'The site pharmacist', 'The monitor', 'The central laboratory', 'The Data Monitoring Committee'];
const VERBS = ['will review', 'must document', 'should confirm', 'will record', 'is responsible for', 'will assess', 'must report', 'will verify'];
const OBJECTS = [
  'all adverse events',
  'the dosing diary',
  'vital signs at each visit',
  'concomitant medications',
  'laboratory results',
  'protocol deviations',
  'drug accountability records',
  'the informed consent form',
];
const TAILS = ['within {n} days', 'at Week {n}', 'every {n} weeks', 'for at least {n} months', 'no later than Day {n}', 'before Visit {n}'];
const MOVED_A = 'Moved paragraph A: the randomization list will be generated by an independent statistician and held by the IRT vendor.';
const CHAPTERS = ['Background', 'Objectives', 'Study Design', 'Population', 'Treatments', 'Assessments', 'Safety', 'Statistics', 'Data Handling', 'Quality'];
const SUBS = ['Overview', 'Procedures', 'Responsibilities', 'Timing', 'Documentation'];

export function largeCase(): DiffResult {
  const rnd = mulberry32(20261007);
  const pick = <T,>(a: T[]) => a[Math.floor(rnd() * a.length)];
  const num = () => 2 + Math.floor(rnd() * 40);
  const sentence = (n = num()) => `${pick(SUBJECTS)} ${pick(VERBS)} ${pick(OBJECTS)} ${pick(TAILS).replace('{n}', String(n))}.`;
  const para = () => {
    const k = 2 + Math.floor(rnd() * 3);
    const nums = Array.from({ length: k }, () => num());
    // Pick the wording once, so text(changedNumbers) differs only in the numbers.
    const parts = nums.map(() => [pick(SUBJECTS), pick(VERBS), pick(OBJECTS), pick(TAILS)]);
    return { nums, text: (ns: number[]) => ns.map((n, i) => `${parts[i][0]} ${parts[i][1]} ${parts[i][2]} ${parts[i][3].replace('{n}', String(n))}.`).join(' ') };
  };

  const CH = 60;
  const SUBN = 5;
  const PER = 8;
  const total = CH * SUBN * PER;
  const pickSet = (count: number, exclude: Set<number>) => {
    const s = new Set<number>();
    while (s.size < count) {
      const i = 10 + Math.floor(rnd() * (total - 20));
      if (!exclude.has(i)) s.add(i), exclude.add(i);
    }
    return s;
  };
  const used = new Set<number>();
  const modified = pickSet(40, used);
  const inserted = pickSet(10, used);
  const deleted = pickSet(10, used);
  const tableCellChanges = new Set([3, 9, 14, 21, 27, 33, 38, 44, 50, 57]);
  const tableRowInserts = new Set([6, 25, 48]);

  const b = new PairBuilder({
    oldName: '07-long-document_old.docx',
    newName: '07-long-document_new.docx',
    lists: { L: { levels: ['1.', 'a)'] } },
    oldSections: [{ header: { default: 'CX-900 Protocol', first: 'Sponsor logo' }, footer: 'Page {PAGE}' }],
    newSections: [{ header: { default: 'CX-900 Protocol', first: 'Sponsor logo' }, footer: 'Page {PAGE}' }],
    pendingRevisionsInNew: 12,
    newRevisions: { accepted: [{ type: 'Inserted and deleted text', count: 12 }], unsupported: [] },
  });
  b.same(Title('Clinical Study Protocol CX-900 — Long Document'), P('Generated mock: 60 chapters, about 3,000 blocks, for performance checks.'));

  let g = 0;
  for (let c = 0; c < CH; c++) {
    b.same(H(1, `${c + 1}. ${CHAPTERS[c % CHAPTERS.length]} ${Math.floor(c / CHAPTERS.length) + 1}`));
    for (let s = 0; s < SUBN; s++) {
      b.same(H(2, `${c + 1}.${s + 1} ${SUBS[s]}`));
      for (let p = 0; p < PER; p++, g++) {
        const x = para();
        if (c === 5 && s === 1 && p === 2) {
          b.moveFrom('m1', P(MOVED_A));
          continue;
        }
        if (c === 21 && s === 3 && p === 4) b.moveTo('m1', P(MOVED_A));
        if (c === 30 && s === 0 && p === 1) b.moveTo('m2', P('Moved paragraph B: emergency unblinding is available through the IRT system at all times.'));
        if (c === 44 && s === 2 && p === 6) {
          b.moveFrom('m2', P('Moved paragraph B: emergency unblinding is available through the IRT system at all times.'));
          continue;
        }
        if (modified.has(g)) {
          const ns = [...x.nums];
          const i = Math.floor(rnd() * ns.length);
          ns[i] = ns[i] + 1 + Math.floor(rnd() * 10);
          b.modified(P(x.text(x.nums)), P(x.text(ns)));
        } else if (deleted.has(g)) b.deleted(P(x.text(x.nums)));
        else b.same(P(x.text(x.nums)));
        if (inserted.has(g)) b.inserted(P(`New in this version: ${sentence()}`));
        if (p === 5 && s === 2) b.same(LI('L', 0, sentence()), LI('L', 0, sentence()), LI('L', 1, sentence()));
      }
    }
    // One table per chapter.
    b.same(P(`Table ${c + 1} summarises the visit schedule for this chapter.`));
    b.tablePair([2600, 2000, 2000, 2000], (r) => {
      r.same({ cells: ['Visit', 'Day', 'Window', 'Procedures'], header: true });
      for (let k = 1; k <= 10; k++) {
        const row = [`Visit ${k}`, String(k * 7), `±${1 + (k % 3)} days`, k % 2 ? 'Vitals, labs' : 'Vitals'];
        if (tableCellChanges.has(c) && k === 4) r.pair(row, [row[0], row[1], `±${2 + (k % 3)} days`, row[3]]);
        else r.same(row);
        if (tableRowInserts.has(c) && k === 6) r.inserted([`Visit 6b`, String(k * 7 + 3), '±1 days', 'Unscheduled ECG']);
      }
    });
  }
  return b.build();
}
